databases:
  - name: testguru
    databaseName: testguru
    ipAllowList: []

services:
  - type: web
    name: testguru
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: test-guru
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
